### ISSUE TITLE
Create App

### ISSUE THREAD

**Issue by EliseBtl** [EliseBtl/THP2_Back#1]
### Why ?
Creating the app, _"the right way"_ will help the process as changing the default after is a bit tedious/difficult in rails.

### Must have:
- [ ] Postgresql
- [ ] No front
- [ ] No Tests framework

### Todo
- [ ] Read through the `rails new --help` documentation
- [ ] Create the app

#### What is rails api mode
- [ ] http://guides.rubyonrails.org/api_app.html
#### What is a middleware
- [ ] http://railscasts.com/episodes/151-rack-middleware
- [ ] http://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack
