### ISSUE TITLE
Create the lesson controller

### ISSUE THREAD

**Issue by EliseBtl** [EliseBtl/THP2_Back#9]
### Why ?
Finally a controller so we can talk to the outer world \o/

We will use ActiveModel Serializer as it allows us to separate our concern. Its neither the role of a model nor a controller to take care of how to serialize as Json a model.

We will use Postman as a way to generate playable documentation and also to test manually our API.

Our API will be nicely constructed and will return nice errors and proper http response code.

### Must have
  - [ ] Serializer for lessons
  - [ ] Fully tested restful controller
  - [ ] Exported postman collection in `docs` directory
### Todo
**Serializer**
  - [ ] Add AMS (https://github.com/rails-api/active_model_serializers)
  - [ ] Do not configure it for now leave default settings
  - [ ] Add a new serializer for the model with id,title, description and created_at

**Controller**
  - [ ] Routing: resource must have everything but `new` and `edit`
  - [ ] Implement those using AMS to return json

**Test it with Postman**
https://www.getpostman.com/ You can save request in Postman in a collection.

Create one for this app it will help you a lot.

**Test it with Rspec**

  - [ ] Test every route with rspec
  - [ ] Test weird cases and error cases (user giving no title, too long title, …)
  - [ ] You can use the json_response helper

### API spec

  - resource name: `lessons`

**`GET` on `/`**
Returns a list of serialized lessons. Respond with a 200

**`POST` on `/`**
Creates a new lesson and returns it.
Respond with a 201

If the lesson is not valid, or if there's a missing param, it should return a error message with the actual error and respond with a 403.

(You should validate params with rails [strong parameters](http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters) and add a `rescue_from` in `app/controllers/application.rb`)

**`GET` on `/:id`**
Returns the right lesson. Respond with a 200.
If the lesson can't be found, respond with a proper error and a 404.
(For this I advise you add a rescue_from in app/controllers/application.rb)

**`PATCH` on `/:id`**
Update the lesson and returns it. Respond with a 200.
Same errors as create

**`DELETE` on `/:id`**
Delete the right lesson. Respond with a 204
If the lesson doesn't exist, respond with a 404.

### Reading List
- http://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html
- http://guides.rubyonrails.org/routing.html
- https://spring.io/understanding/REST
- http return codes: https://http.cat/ (We will mostly use: 404, 403, 401, 200, 201, 202, 204)
